name = "D3Q19Model"
uuid = "c5225bfb-2b2e-4afb-b95e-4df3ded744e8"
authors = ["shiyibai5315"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
